apiVersion: v1
baseDomain: {{ otlc_service_info.top_level_domain }}
compute:
- hyperthreading: Enabled
  name: worker
  platform: {}
  replicas: 3
controlPlane:
  hyperthreading: Enabled
  name: master
  platform: {}
  replicas: 3
metadata:
  creationTimestamp: null
  name: cluster-{{ otlc_service_info.guid }}
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineCIDR: 10.0.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  aws:
    region: {{ otlc_service_info.aws_region }}
pullSecret: '{{ redhat_cloud_pull_secret }}'
sshKey: {{ ssh_public_key.stdout }}
{% if otlc_ocp4_additional_trust_bundle is defined %}
additionalTrustBundle: |
  {{ otlc_ocp4_additional_trust_bundle | indent(2) }}
{% endif %}
