- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - import_role:
        name: otlc_ocs4_implementation_order
      vars:
        otlc_service_desc: '{{ otlc_labs.ocs4_implementation }}'
