- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - import_role:
        name: otlc_acm_foundation_managed_order
      vars:
        otlc_service_desc: '{{ otlc_labs.acm_foundation_managed }}'
