- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - import_role:
        name: otlc_ocp4_configuration_order
      vars:
        otlc_service_desc: '{{ otlc_labs.ocp4_configuration }}'
