roles:
- name: ansible-modules-hashivault
  src: https://github.com/TerryHowe/ansible-modules-hashivault.git
  version: 4.6.2
  # requires rpm package python3-hvac

- name: devnullcake.redhat-subscription
  src: https://github.com/noseka1/ansible-role-redhat-subscription.git
  version: master

- name: mprahl.lets-encrypt-route-53
  src: https://github.com/noseka1/ansible-role-lets-encrypt-route-53.git
  version: master
  # requires EPEL enabled

collections:
- name: community.kubernetes
  src: https://github.com/ansible-collections/community.kubernetes.git
  version: 1.1.1
