# For this playbook ovirtsdk4 version 4.4.0 or higher is required. You can install it using:
# $ pip install ovirt-engine-sdk-python
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - import_role:
        name: rhv_lab
        tasks_from: create_ovirt_network.yml
