- name: Create namespace
  command: oc apply --kustomize {{ loki_kustomizations.namespace }}

- name: Deploy MinIO
  command: oc apply --kustomize {{ loki_kustomizations.minio }}

- name: Deploy Loki
  command: oc apply --kustomize {{ loki_kustomizations.loki }}

- name: Deploy Promtail
  shell: kustomize build {{ loki_kustomizations.promtail }} | oc apply --filename -
