apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ vault_name }}-unseal-script
  namespace: {{ vault_namespace }}
data:
  run.sh: |
    #!/bin/bash
    echo VAULT_ADDR is $VAULT_ADDR
    while true; do
      STATUS=$(curl --insecure --silent --show-error --location $VAULT_ADDR/v1/sys/seal-status | jq --raw-output '.sealed')
      if [ "$STATUS" = "true" ]; then
        echo $(date) Vault sealed, unsealing!
        KEY=$(cat /mnt/key)
        curl \
        --insecure \
        --silent \
        --show-error \
        --location \
        --request PUT \
        --data "{\"key\":\"$KEY\"}" \
        $VAULT_ADDR/v1/sys/unseal
        echo Unseal returned $?
      fi
      sleep 10
    done
