apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ vault_name }}
  namespace: {{ vault_namespace }}
spec:
  port:
    targetPort: 8200
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: {{ vault_name }}
