- name: Prepare request options
  set_fact:
    request_options:
      href: '/api/service_templates/{{ otlc_service_desc.template_id }}'

- name: Add additional request options
  set_fact:
    request_options: '{{ request_options | combine(otlc_service_desc.order_options | default({})) }}'

- name: Show request options
  debug:
    var: request_options

- name: Ordering {{ otlc_service_desc.template_name }} from the catalog {{ otlc_service_desc.catalog_name }}
  uri:
    url: 'https://labs.opentlc.com/api/service_catalogs/{{ otlc_service_desc.catalog_id }}/service_templates'
    user: '{{ otlc_username }}'
    password: '{{ otlc_password }}'
    method: POST
    body:
      action: order
      resource: '{{ request_options }}'
    body_format: json
    status_code: 200
  register: opentlc_order

- debug: msg='Request URL is {{ opentlc_order.json.results.0.href }}'

- name: Waiting since {{ lookup("pipe", "date +%r") }} for the lab provisioning to complete
  uri:
    url: '{{ opentlc_order.json.results.0.href }}'
    user: '{{ otlc_username }}'
    password: '{{ otlc_password }}'
    method: GET
    status_code: 200
  register: result
  ignore_errors: True
  until: result.json is defined and result.json.request_state == 'finished'
  retries: '{{ otlc_order_wait_retries }}'
  delay: 10
