- name: Set up cluster-wide proxy to trust the certificate
  k8s:
    definition: "{{ lookup('template', '{{ item }}') }}"
  loop:
    - user-ca-bundle-cm.yml
    - cluster-proxy.yml

- name: Create the certificate secrets
  k8s:
    definition: "{{ lookup('template', 'cert-secret.yml') }}"
  no_log: True
  with_items:
    - { name: api-cert,      namespace: openshift-config,  crt: '{{ crc_lab_certs.api.crt }}',     key: '{{ crc_lab_certs.api.key }}' }
    - { name: wildcard-cert, namespace: openshift-ingress, crt: '{{ crc_lab_certs.ingress.crt }}', key: '{{ crc_lab_certs.ingress.key }}' }

- name: Configure API server certificate
  k8s:
    definition: "{{ lookup('template', 'cluster-apiserver.yml') }}"

- name: Configure wildcard apps certificate
  k8s:
    definition: "{{ lookup('template', 'default-ingresscontroller.yml') }}"
