- name: Deploy ocs operator
  command: oc apply --kustomize {{ ocs_kustomizations.operator }}

- name: Wait for OCS operator to deploy
  import_role:
    name: openshift_common
    tasks_from: wait_for_operator.yml
  vars:
    subscription_name: '{{ ocs_subscription_name }}'
    subscription_namespace: '{{ ocs_subscription_namespace }}'

- name: Deploy ocs instance
  command: oc apply --kustomize {{ ocs_kustomizations.instance }}

- name: Waiting since {{ lookup("pipe", "date +%r") }} for {{ ocs_instance_name }} deployment to complete
  k8s_info:
    api_version: ocs.openshift.io/v1
    kind: StorageCluster
    namespace: '{{ ocs_instance_namespace }}'
    name: '{{ ocs_instance_name }}'
  register: ocs_instance
  until:
    - ocs_instance.resources.0.status is defined
    - ocs_instance.resources.0.status.conditions | selectattr('type', 'equalto', 'Available') | list | length > 0
    - (ocs_instance.resources.0.status.conditions | selectattr('type', 'equalto', 'Available') | first).status == "True"
  retries: 60
  delay: 10

- name: Deploy rook-ceph-tools
  k8s:
    definition:
      apiVersion: ocs.openshift.io/v1
      kind: OCSInitialization
      metadata:
        name:  ocsinit
        namespace: '{{ ocs_instance_namespace }}'
      spec:
        enableCephTools: true
