kubeadm_config:
  # see git tags at https://github.com/kubernetes/kubernetes
  kubernetes_version: v1.21.1
  # required by flannel, see also: https://github.com/coreos/flannel/blob/master/Documentation/kubernetes.md
  pod_network_cidr: 10.244.0.0/16
  crisocket: /var/run/dockershim.sock
  #crisocket: /var/run/containerd/containerd.sock
  #crisocket: /var/run/crio/crio.sock

kubeadm_config_dir: '{{ ansible_env["HOME"] }}/kubeadm'

kubeconfig_dir: /root/.kube
kubeconfig_file: '{{ kubeconfig_dir }}/config'

flannel_version: v0.12.0
flannel_url: 'https://raw.githubusercontent.com/coreos/flannel/{{ flannel_version }}/Documentation/kube-flannel.yml'

kubernetes_dashboard_version: v2.0.0
kubernetes_dashboard_url: 'https://raw.githubusercontent.com/kubernetes/dashboard/{{ kubernetes_dashboard_version }}/aio/deploy/recommended.yaml'

ingress_nginx_version: nginx-0.30.0
ingress_nginx_mandatory_url: 'https://raw.githubusercontent.com/kubernetes/ingress-nginx/{{ ingress_nginx_version }}/deploy/static/mandatory.yaml'
ingress_nginx_nodeport_url: 'https://raw.githubusercontent.com/kubernetes/ingress-nginx/{{ ingress_nginx_version }}/deploy/static/provider/baremetal/service-nodeport.yaml'
