- name: Enable generic secret kv store
  hashivault_secret_engine:
    name: kv
    backend: kv
    options: version=2
  environment:
    VAULT_ADDR: '{{ vault_addr }}'
    VAULT_SKIP_VERIFY: '{{ vault_skip_verify }}'
    VAULT_TOKEN: '{{ vault_token }}'
