- name: Grab vault's service account token
  command: oc serviceaccounts get-token --namespace {{ vault_namespace }} {{ vault_name }}
  changed_when: False
  register: token_reviewer_jwt

- name: Grab vault's service account CA
  command: oc exec --namespace {{ vault_namespace }} {{ vault_name }}-0 -- cat /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
  changed_when: False
  register: kubernetes_ca_cert

- name: Grab OpenShift API server URL
  command: oc whoami --show-server
  changed_when: False
  register: kubernetes_host

- name: Enable Kubernetes authentication
  hashivault_auth_method:
    method_type: kubernetes
    state: enabled
  environment:
    VAULT_ADDR: '{{ vault_addr }}'
    VAULT_SKIP_VERIFY: '{{ vault_skip_verify }}'
    VAULT_TOKEN: '{{ vault_token }}'

- name: Configure Kubernetes authentication
  hashivault_write:
    secret: /auth/kubernetes/config
    data:
      token_reviewer_jwt: '{{ token_reviewer_jwt.stdout }}'
      kubernetes_ca_cert: '{{ kubernetes_ca_cert.stdout }}'
      kubernetes_host: '{{ kubernetes_host.stdout }}'
  environment:
    VAULT_ADDR: '{{ vault_addr }}'
    VAULT_SKIP_VERIFY: '{{ vault_skip_verify }}'
    VAULT_TOKEN: '{{ vault_token }}'

- name: Grant read access to all secrets to Kubernetes identities
  hashivault_policy:
    name: kube_read
    rules: |
      path "kv/data/*"
      {
        capabilities = [ "read", "list" ]
      }
  environment:
    VAULT_ADDR: '{{ vault_addr }}'
    VAULT_SKIP_VERIFY: '{{ vault_skip_verify }}'
    VAULT_TOKEN: '{{ vault_token }}'

- name: Define kube role
  hashivault_write:
    secret: /auth/kubernetes/role/kube
    data:
      bound_service_account_names: default
      bound_service_account_namespaces: '*'
      policies: kube_read
  environment:
    VAULT_ADDR: '{{ vault_addr }}'
    VAULT_SKIP_VERIFY: '{{ vault_skip_verify }}'
    VAULT_TOKEN: '{{ vault_token }}'

- name: Define external_secrets role
  hashivault_write:
    secret: /auth/kubernetes/role/external-secrets
    data:
      bound_service_account_names: external-secrets-kubernetes-external-secrets
      bound_service_account_namespaces: external-secrets
      policies: kube_read
  environment:
    VAULT_ADDR: '{{ vault_addr }}'
    VAULT_SKIP_VERIFY: '{{ vault_skip_verify }}'
    VAULT_TOKEN: '{{ vault_token }}'
