- name: Obtain vault route
  k8s_info:
    api_version: route.openshift.io/v1
    kind: Route
    name: '{{ vault_name }}'
    namespace: '{{ vault_namespace }}'
  register: vault_route

- name: Set vault URL
  set_fact:
    vault_addr: 'https://{{ vault_route.resources.0.spec.host }}'
