- name: Add hashicorp chart repo
  community.kubernetes.helm.helm_repository:
    name: hashicorp
    repo_url: "https://helm.releases.hashicorp.com"

- name: Deploy Vault Helm chart
  community.kubernetes.helm:
    name: '{{ vault_name }}'
    chart_ref: hashicorp/vault
    chart_version: '{{ vault_chart_version | default(omit) }}'
    release_namespace: '{{ vault_namespace }}'
    create_namespace: True
    release_values:
      global:
        openshift: True
      server:
        auditStorage:
          enabled: True
        extraEnvironmentVars:
          VAULT_LOG_LEVEL: debug
      ui:
        enabled: True

- name: Create route
  k8s:
    definition: "{{ lookup('template', 'vault-route.yml') }}"

- name: Obtain vault route
  import_tasks: get_vault_route.yml

- name: Waiting since {{ lookup("pipe", "date +%r") }} for vault to come up
  uri:
    url: '{{ vault_addr }}/v1/sys/health'
    method: GET
    validate_certs: '{{ not vault_skip_verify }}'
    status_code: [ 200, 501, 503 ]
  register: vault_health
  until: (vault_health.status in [ 200, 501 ] or (vault_health.json is defined and vault_health.json.sealed))
  retries: 60
  delay: 10
