- name: Add hashicorp chart repo
  community.kubernetes.helm.helm_repository:
    name: hashicorp
    repo_url: "https://helm.releases.hashicorp.com"

- name: Deploy Vault Helm chart
  community.kubernetes.helm:
    name: '{{ vault_name }}'
    chart_ref: hashicorp/vault
    release_namespace: '{{ vault_namespace }}'
    create_namespace: True
    release_values:
      global:
        openshift: True
      server:
        auditStorage:
          enabled: True
        extraEnvironmentVars:
          VAULT_LOG_LEVEL: debug
      ui:
        enabled: True

- name: Create route
  k8s:
    definition: "{{ lookup('template', 'vault-route.yml') }}"

- name: Obtain vault route
  k8s_info:
    api_version: route.openshift.io/v1
    kind: Route
    name: '{{ vault_name }}'
    namespace: '{{ vault_namespace }}'
  register: vault_route

- name: Set vault URL
  set_fact:
    vault_addr: 'https://{{ vault_route.resources.0.spec.host }}'

- name: Waiting since {{ lookup("pipe", "date +%r") }} for vault to come up
  uri:
    url: '{{ vault_addr }}/v1/sys/health'
    method: GET
    validate_certs: '{{ not vault_skip_verify }}'
    status_code: [ 200, 501, 503 ]
  register: vault_health
  until: (vault_health.status in [ 200, 501 ] or vault_health.json.sealed)
  retries: 60
  delay: 10
