- name: Install vault on OpenShift
  import_tasks: install.yml

- name: Initialize vault
  import_tasks: initialize.yml
  when: vault_health.status == 501

- name: Ensure vault is unsealed
  import_tasks: unseal.yml

- name: Retrieve admin token
  import_tasks: get_admin_token.yml

- name: Enable the Kubernetes auth method
  import_tasks: enable_kube_auth.yml

- name: Enable audit logs
  import_tasks: enable_audit.yml

- name: Insert secrets
  import_tasks: insert_secrets.yml

- name: Vault installed successfully
  debug:
    msg: Vault installed successfully. You can log in with 'VAULT_ADDR={{ vault_addr }} VAULT_SKIP_VERIFY={{ vault_skip_verify }} vault login -method=userpass username=admin password=<password>'
