- name: Create subscription-admins group
  k8s:
    definition: "{{ lookup('template', 'open-cluster-management-subscription-admins-group.yml') }}"

- name: Add the subscription-admins group the the existing open-cluster-management:subscription-admin binding
  k8s:
    definition: "{{ lookup('template', 'open-cluster-management:subscription-admin-clusterrolebinding.yml') }}"
