- name: Deploy RHACM operator
  command: oc apply --kustomize {{ rhacm_kustomizations.operator }}

- name: Wait for RHACM operator to deploy
  import_role:
    name: openshift_common
    tasks_from: wait_for_operator.yml
  vars:
    subscription_name: '{{ rhacm_subscription_name }}'
    subscription_namespace: '{{ rhacm_subscription_namespace }}'

- name: Wait until klusterletaddonconfigs resource is available
  k8s_info:
    api_version: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: klusterletaddonconfigs.agent.open-cluster-management.io
  register: klusterletaddonconfigs_crd
  until: klusterletaddonconfigs_crd.resources | length > 0
  retries: 80
  delay: 10

- name: Deploy RHACM instance
  command: oc apply --kustomize {{ rhacm_kustomizations.instance }}

- name: Waiting since {{ lookup("pipe", "date +%r") }} for {{ rhacm_instance_name }} deployment to complete
  k8s_info:
    api_version: operator.open-cluster-management.io/v1
    kind: MultiClusterHub
    namespace: '{{ rhacm_instance_namespace }}'
    name: '{{ rhacm_instance_name }}'
  register: rhacm_instance
  until:
    - rhacm_instance.resources | length > 0
    - rhacm_instance.resources.0.status is defined
    - rhacm_instance.resources.0.status.conditions | selectattr('type', 'equalto', 'Complete') | list | length > 0
    - (rhacm_instance.resources.0.status.conditions | selectattr('type', 'equalto', 'Complete') | first).status == "True"
  retries: 80
  delay: 10
