- import_tasks: install_rhacm_core.yml

- import_role:
    name: openshift_minio
  vars:
    minio_namespace: '{{ rhacm_minio_namespace }}'
  when: install_rhacm_observability

- import_tasks: install_rhacm_observability.yml
  when: install_rhacm_observability

- import_tasks: configure_users.yml

- import_tasks: sync_release_images.yml

- import_tasks: report_success.yml
