- import_tasks: postinstall_kubeconfig.yml

- import_tasks: postinstall_certs.yml

- import_tasks: postinstall_nodes.yml

- import_role:
    name: openshift_common
    tasks_from: postinstall_users.yml

- import_role:
    name: openshift_common
    tasks_from: postinstall_oauth.yml

- import_role:
    name: openshift_common
    tasks_from: postinstall_image_registry.yml

- import_role:
    name: openshift_common
    tasks_from: postinstall_monitoring.yml

- import_role:
    name: openshift_common
    tasks_from: postinstall_alerting.yml

- import_role:
    name: openshift_common
    tasks_from: postinstall_image_prunning.yml

- import_role:
    name: openshift_common
    tasks_from: postinstall_audit.yml
