- name: Create the certificate secrets
  include_tasks: postinstall_certs_create_secret.yml
  with_items:
    - { secret_name: api-cert,      namespace: openshift-config,  common_name:    'api.cluster-{{ otlc_service_info.guid }}.{{ otlc_service_info.top_level_domain }}' }
    - { secret_name: wildcard-cert, namespace: openshift-ingress, common_name: '*.apps.cluster-{{ otlc_service_info.guid }}.{{ otlc_service_info.top_level_domain }}' }

- name: Configure API server certificate
  k8s:
    definition: "{{ lookup('template', 'cluster-apiserver.yml') }}"

- name: Configure wildcard apps certificate
  k8s:
    definition: "{{ lookup('template', 'default-ingresscontroller.yml') }}"
