- name: Fetch the {{ cluster_config_dir }}/auth/kubeconfig file
  slurp:
    src: '{{ cluster_config_dir }}/auth/kubeconfig'
  register: kubeconfig
  become: True

- name: Ensure ~/.kube directory exists
  file:
    path: .kube
    state: directory

- name: Copy kubeconfig to ~/.kube/config
  copy:
    dest: .kube/config
    content: '{{ kubeconfig.content | b64decode }}'

- name: Don't verify API server cert (cert will be replaced with the Let's Encrypt cert)
  command: oc config set-cluster cluster-{{ otlc_service_info.guid }} --insecure-skip-tls-verify=true
