apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: {{ quay_instance_namespace }}

bases:
- {{ quay_kustomizations.instance }}

patchesStrategicMerge:
- quay-quayecosystem.yaml

secretGenerator:
- behavior: replace
  literals:
  - database-username=quay
  - database-password={{ generic_user_password }}
  - database-root-password={{ generic_user_password }}
  - database-name=quay
  name: database
- behavior: replace
  literals:
  - config-app-password={{ generic_user_password }}
  name: quayconfig
- behavior: replace
  literals:
  - password={{ generic_user_password }}
  name: redis
- behavior: replace
  literals:
  - superuser-email=quay@redhat.com
  - superuser-password={{ generic_user_password }}
  - superuser-username=quay
  name: superuser
- behavior: replace
  files:
  - .dockerconfigjson=redhat-quay-pull-secret.json
  name: redhat-quay-pull-secret
  type: kubernetes.io/dockerconfigjson
