apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ argocd_instance_name }}-tls-certs-cm
  namespace: {{ argocd_instance_namespace }}
data:
  kubernetes.default.svc: |
    {{ sa_secrets.resources.0.data['ca.crt'] | b64decode | indent(4) }}
