service_mesh_kustomizations:
  elasticsearch_operator: github.com/noseka1/service-mesh-kustomization/elasticsearch-operator/base?ref=myauto
  jaeger_operator: github.com/noseka1/service-mesh-kustomization/jaeger-operator/base?ref=myauto
  kiali_operator: github.com/noseka1/service-mesh-kustomization/kiali-operator/base?ref=myauto
  service_mesh_operator: github.com/noseka1/service-mesh-kustomization/service-mesh-operator/base?ref=myauto
  service_mesh_instance: github.com/noseka1/service-mesh-kustomization/service-mesh-instance/overlays/development?ref=myauto

service_mesh_subscription_name: servicemeshoperator
service_mesh_subscription_namespace: openshift-operators
service_mesh_instance_name: control-plane
service_mesh_instance_namespace: istio-system
