vault_namespace: vault
vault_name: vault
vault_skip_verify: true

rhacm_vault_cluster:
  base_domain: mycluster.example.com
  aws_region: us-east-2
  aws_access_key_id: XXXXXXXXXXXXXXXXXXXX
  aws_secret_access_key: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
