apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ external_secrets_name }}-test
  namespace: {{ external_secrets_namespace }}
spec:
  backendType: vault
  kvVersion: 2
  data:
  - name: testkey
    key: kv/data/mysecret
    property: testkey
