- name: Order the service
  import_role:
    name: otlc_generic_order

- set_fact:
    otlc_service_raw:
      guid: '{{ (otlc_service_attributes.json.custom_attributes | selectattr("name", "equalto", "GUID") | first).value }}'
      env0: '{{ (otlc_service_attributes.json.custom_attributes | selectattr("name", "equalto", "Environment Info 000") | first).value }}'
      env1: '{{ (otlc_service_attributes.json.custom_attributes | selectattr("name", "equalto", "Environment Info 001") | first).value }}'
      env2: '{{ (otlc_service_attributes.json.custom_attributes | selectattr("name", "equalto", "Environment Info 002") | first).value }}'
      env3: '{{ (otlc_service_attributes.json.custom_attributes | selectattr("name", "equalto", "Environment Info 003") | first).value }}'
      env4: '{{ (otlc_service_attributes.json.custom_attributes | selectattr("name", "equalto", "Environment Info 004") | first).value }}'
      env5: '{{ (otlc_service_attributes.json.custom_attributes | selectattr("name", "equalto", "Environment Info 005") | first).value }}'
      env6: '{{ (otlc_service_attributes.json.custom_attributes | selectattr("name", "equalto", "Environment Info 006") | first).value }}'
      aws_region: '{{ (otlc_service_attributes.json.custom_attributes | selectattr("name", "equalto", "ec2region") | first).value }}'

- set_fact:
    otlc_service_info:
      guid:                  '{{ otlc_service_raw.guid }}'
      top_level_domain:      '{{ otlc_service_raw.env0.split(":").1 | trim | regex_replace("^\.", "")}}'
      aws_access_key_id:     '{{ otlc_service_raw.env3.split("=").1 | trim }}'
      aws_secret_access_key: '{{ otlc_service_raw.env4.split("=").1 | trim }}'
      ssh_username:          '{{ otlc_service_raw.env5.split(" ").3.split("@").0 | trim }}'
      ssh_hostname:          '{{ otlc_service_raw.env5.split(" ").3.split("@").1 | trim }}'
      ssh_password:          '{{ otlc_service_raw.env6.split(":").1 | trim }}'
      aws_region:            '{{ otlc_service_raw.aws_region }}'

- debug:
    var: otlc_service_info
