apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: argocd-server
spec:
  port:
    targetPort: https
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: argocd-server
