apiVersion: v1
kind: Secret
metadata:
  name: '{{ item.secret_name }}'
  namespace: '{{ item.namespace }}'
data:
  tls.crt: '{{ cert_pem_file.content }}'
  tls.key: '{{ cert_key_file.content }}'
type: kubernetes.io/tls
