apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- {{ rhacm_kustomizations.observability }}

patchesStrategicMerge:
- pull-secret-secret.yaml
- thanos-object-storage-secret.yaml
