apiVersion: v1
kind: Secret
metadata:
  name: thanos-object-storage
stringData:
  thanos.yaml: |
    type: s3
    config:
      bucket: mybucket-1
      endpoint: {{ minio_route.resources.0.spec.host }}
      access_key: admin
      secret_key: {{ generic_user_password }}
      insecure: false
      http_config:
        insecure_skip_verify: true
