- name: Set admin user password
  k8s:
    definition: "{{ lookup('template', item) }}"
  loop:
    - '{{ argocd_instance_name }}-cluster-secret.yaml'

- name: Obtain ingress wildcard certificate
  k8s_info:
    api_version: v1
    kind: Secret
    name: wildcard-cert
    namespace: openshift-ingress
  register: wildcard_cert

- name: Configure Argo CD endpoint TLS cert
  k8s:
    definition: "{{ lookup('template', '{{ argocd_instance_name }}-tls-secret.yaml') }}"
  when: wildcard_cert.resources | length == 1

- name: Configure Argo CD server
  k8s:
    definition: "{{ lookup('template', 'argocd-cm-cm.yaml') }}"
