- name: Obtain Argo CD route
  k8s_info:
    api_version: route.openshift.io/v1
    kind: Route
    name: '{{ argocd_instance_name }}-server'
    namespace: '{{ argocd_instance_namespace }}'
  register: argocd_route

- name: Waiting since {{ lookup("pipe", "date +%r") }} for Argo CD to come up
  uri:
    url: 'https://{{ argocd_route.resources.0.spec.host }}/api/v1/session'
    method: POST
    body:
      username: admin
      password: '{{ generic_user_password }}'
    body_format: json
    validate_certs: False
  register: result
  until: result.status == 200
  retries: 60
  delay: 10

- debug:
    msg: Argo CD installed successfully. You can log in with 'argocd login --insecure {{ argocd_route.resources.0.spec.host }} --username admin'
